CONTINUE = 'Continue'

TAB_GROUP = '-TABGROUP-'
EXPAND = '-EXPAND-'
STATUS_MESSAGE = '-STATUS_MESSAGE-'

Q_DATABASE_CORRUPT = 'Database is corrupt'
CMD_DB_ACTION_PARAMETERS = ' Parameters '

# Commands
CMD_START = f' Compare '
CMD_OK = ' OK '

CMD_ADD_REPO = ' + '
CMD_DELETE_REPO = ' - '
CMD_CLEAR_REPO = ' 0 '

CMD_ADD_FILE_NAME = ' Add '
CMD_DELETE_FILE_NAME = ' Delete '
CMD_CLEAR_FILE_NAME = ' Clear '
CMD_FACTORY_RESET = ' Factory reset'

# Tabs
TAB_START = 'Start'
TAB_PARMS = 'Parameters'

FRAME_REPOSITORIES = '-FRAME_REPOSITORIES-'
FRAME_COMPARE_PATHS = '-FRAME_COMPARE_PATHS-'
FRAME_REPO_BUTTONS = '-REPO_BUTTONS-'
FRAME_COMPARE_BUTTONS = '-COMPARE_BUTTONS-'
FRAME_OUTPUT_PARMS = '-OUTPUT_PARMS-'

# Display
FONT_FAMILY = 'Verdana'
FONT_SIZE = 12
FONT = (FONT_FAMILY, FONT_SIZE)
FONT_BIG = (FONT_FAMILY, FONT_SIZE + 2)
FONT_HUGE = (FONT_FAMILY, FONT_SIZE + 4)
FONT_TABLE = 'Arial 10'

# Behavior
TABLE_JUSTIFY = 'left'
BUTTONS_JUSTIFY = 'right'

POPUP_WIDTH_MAX = 132
POPUP_AUTO_CLOSE_DEFAULT = 4

# X1 = max( len( v ) for v in config_desc_dicts() )
X1 = None
X2 = 20

Y1 = 1
P = 20
P1 = (5, 5)

STATUSBAR_WIDTH = 132

# PopUp text
INFO = 'Information'
WARNING = 'Warning'
ERROR = 'Error'
