THEME = 'DarkBlue14'  # DarkBlue14, BlueMono, DarkBlue

COLOR_OK = 'Green'
COLOR_WARNING = 'Orange'
COLOR_ERROR = 'Red'
COLOR_TEXT = 'Black'
BUTTON_COLOR_TEXT = 'White'

TABLE_COLOR_BACKGROUND = 'Light Grey'
TABLE_COLOR_TEXT = 'Black'
TABLE_COLOR_SELECTED_ROW = ('White', 'DarkBlue')

STATUSBAR_COLOR_BACKGROUND = 'Black'
STATUSBAR_COLOR_INFO = 'LightGreen'

POPUP_COLOR_BACKGROUND = 'alice blue'

COLOR_TEXT_DISABLED = 'DarkBlue'
COLOR_LABEL_DISABLED = 'Grey30'
COLOR_BACKGROUND_DISABLED = TABLE_COLOR_BACKGROUND
